
name: Bug Report
description: File a bug report
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of ibis-substrait are you using?
      placeholder: "Ex: 2.18.0"
    validations:
      required: true
  - type: textarea
    id: backends
    attributes:
      label: What substrait consumer(s) are you using, if any?
      placeholder: "Ex: DuckDB, PyArrow, Velox"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output or tracebacks. This will be automatically formatted into code, so no need for backticks.
      render: "sh"
