name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        if: ${{ fromJSON(steps.needs-pr.outputs.did-change) }}
        id: generate-token
        with:
          app_id: ${{ secrets.SQUAWK_BOT_APP_ID }}
          private_key: ${{ secrets.SQUAWK_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v2

      - uses: renovatebot/github-action@v31.68.1
        with:
          configurationFile: .renovate.json
          token: 'x-access-token:${{ steps.generate-token.outputs.token }}'
        env:
          PYTHONHASHSEED: "0"
